### ISSUE TITLE
About SGDET_on_cutom_images.ipynb

### ISSUE THREAD

**Issue by G200005** [Maelic/SGG-Benchmark#42]
hello，Thank you very much for your work in the SGG domain.I'm getting some strange errors when running the code as follows.
![image](https://github.com/user-attachments/assets/be650497-1c23-4efa-8097-50e25aea7d66)
![image](https://github.com/user-attachments/assets/20c488fa-32a2-4031-adf5-250eec8b950a)
![image](https://github.com/user-attachments/assets/84ec36a2-d9bd-4c40-806a-7c9f63e00c74)
I have changed the relevant configuration file in `SGDET_on_cutom_images.ipynb` using absolute paths and the configuration file was also obtained by training the model using the code you provided, but the error message prompts me that`. /checkpoints/causal-motifs-sgdet-exmp` does not exist and I am confused as to why this is. As you can see in the image`. /checkpoints/causal-motifs-sgdet-exmp` is present.

**Comment by Maelic** [comment]
Hello, the ```SGDET_on_cutom_images.ipynb``` notebook is outdated, please use [this one instead](https://github.com/Maelic/SGG-Benchmark/blob/main/demo/SGDET_on_cutom_images.ipynb).
You can also customize [this file](https://github.com/Maelic/SGG-Benchmark/blob/main/demo/demo_model.py) for better visualization.

**Comment by G200005** [comment]
Hi, I just tried your latest release `demo/SGDET_on_cutom_images.ipynb` but as soon as I run it I get the following error.
![image](https://github.com/user-attachments/assets/8ad26561-e3e6-47ec-ae86-73a88dedb1cd)
I just changed the relevant configuration file.
![image](https://github.com/user-attachments/assets/f1603c69-9a54-491f-bccb-b67bc1ea5622)
I tried to pass parameters for `SSG_Model` using the following method but got an error.
![image](https://github.com/user-attachments/assets/8fc46ec2-1d0c-4cbf-addc-b14a407830f6)
![image](https://github.com/user-attachments/assets/6302147e-3c90-4389-b93d-47e371057daf)
I checked `demo_model.py` about the instantiation process of` SGG_Model`, but still not resolved. I am also not sure what is the difference between weight_path and weights, thanks again for your patience.

**Comment by Maelic** [comment]
I think you have to update the file [demo_model.py](https://github.com/Maelic/SGG-Benchmark/blob/main/demo/demo_model.py) as well, I just pushed a new version of it.

**Comment by G200005** [comment]
Yes, I also updated `demo_model.py` synchronously, but I still get the above error.

**Comment by G200005** [comment]
Thank you very much for your patience in answering. Currently the code is no longer reporting errors, but the visualisation is having a bit of a problem, showing that no objects or relationships are detected when using the latest` demo_model.py` and `SGDET_on_cutom_images.ipynb` that you provided, which is quite puzzling.
![image](https://github.com/user-attachments/assets/45ee5925-2305-42d5-bb05-e7bd5f735b47)
![image](https://github.com/user-attachments/assets/e045faad-d3dd-4cd9-84fc-d275b44cdd56)
The same config file and weight file, using the visualisation file you provided earlier gives the following result.Although very few relationships were detected.
![image](https://github.com/user-attachments/assets/ce850c9a-06c9-4930-b247-90455b28aa69)
Incidentally the training command I used was
```
CUDA_VISIBLE_DEVICES=6 python tools/relation_train_net.py \
    --task sgdet \
    --save-best  \
    --config-file "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" \
    MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor \
    MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE none \
    MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum \
    MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs  \
    SOLVER.IMS_PER_BATCH 8 \
    TEST.IMS_PER_BATCH 1 \
    DTYPE "float16" \
    SOLVER.MAX_EPOCH 20 \
    MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/pretrained_faster_rcnn/model_final.pth \
    OUTPUT_DIR ./checkpoints/causal-motifs-sgdet-exmp 2>&1 | tee train_vg_tde.log
```
The config file and the weight file obtained by this training script do not yield satisfactory visualisations. What should I do if I want to visualise better and get more fine-grained predicate relations? Do you have any better suggestions, thanks again.

**Comment by Maelic** [comment]
If you have no predictions, try to reduce the rel_conf and box_conf values in the notebook. If you are using Faster-RCNN, I would recommend to put box_conf to the minimum (like 0.01) and rel_conf around 0.05.
Alternatively, you can download and try my latest model REACT by downloading the weights provided in [MODEL_ZOO.md](https://github.com/Maelic/SGG-Benchmark/blob/main/MODEL_ZOO.md).

**Comment by G200005** [comment]
Thanks a lot.I admire your creativity and excellent coding skills. Thank you for your contribution to the field of SGG.I have some opinions that represent my personal aesthetics only.I consulted my colleagues in the lab, and we have always thought that the results obtained from the previous version of the visualisation code showed the semantic relationships of the images more clearly, as shown in the first image. The current version of the code gives a less clear visualisation, as shown in the second image.I would be very happy if my comments help you with your project.
The result of the visualisation, which we have always found to be clearer, is shown in the following figure
![image](https://github.com/user-attachments/assets/5c96cfeb-7f9b-46c0-b8ad-14fd85b875be)

![image](https://github.com/user-attachments/assets/9f9d7d6f-ebad-4e88-88cb-77cda71b3454)

**Comment by Maelic** [comment]
Thank you for your feedback, originally I created this new visualization for the webcam demo, because it is easier to visualize the graph in real time directly on the image. But yes the previous visualization is better for images.

Good luck on your project! Don't hesitate to cite my work if you are using it :)

**Comment by G200005** [comment]
I will be using your visualisation in my project presentation and referencing it! I hope more scholars in the SGG field will notice the value of your work. However, I still have some questions, I would like to use the previous version of the visualisation code for the effect demo, but I find that just changing the latest weight paths you provided seems to give an error. I would like to get this visualisation below using the relevant files from` react_final`. I tried to modify the `demo_model.py` but got errors.What should I do?
![025e6c560b0b68b09d2c16b9e792c62](https://github.com/user-attachments/assets/b1a49998-06dd-4ea4-8859-51e35b3ec243)
It would be exciting if the visualisations were of this form and could get more fine-grained predicates like the REACT model.

**Comment by Maelic** [comment]
Hi,
I just pushed a new version which should solve your problem. Now you can switch from one visualization to the other with the variable ```visu_type```. ```visu_type='image'``` will give the old visualization (the one you want) and ```visu_type='video'``` is the new one.
Thank you for your interest in my work!

**Comment by G200005** [comment]
It's really great! I tried your latest released weights and he was able to get more object detection results and get object categories like **pavement** that didn't appear in VG150 compared to the results from training on the VG150 dataset.Thank you for your work, it's really great.

**Comment by Maelic** [comment]
Hi,

This is because I changed a lot the codebase recently, you can remove the key `LOGIT_ADJUSTMENT` from the config file `config.yml` and it should work like a charm.

**Comment by Koralion** [comment]
after removing a lot of heads in the config file it still showed

RuntimeError: Error(s) in loading state_dict for GeneralizedYOLO:
	size mismatch for roi_heads.relation.union_feature_extractor.feature_extractor.pooler.reduce_channel.0.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 576, 3, 3]).
